# FROM node:alpine
# WORKDIR '/app'
# COPY ./package.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "run","start"]


FROM node:alpine

USER node
RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node package.json /home/node/app
RUN npm install

COPY --chown=node:node . /home/node/app
RUN cd /home/node/app
CMD ["npm", "run", "start"]
