sudo: required
services:
  - docker

before_install:
  - docker build -t seanlucas94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true seanlucas94/react-test npm test -- --coverage

after_success:
  - docker build -t seanlucas94/multi-client ./client
  - docker build -t seanlucas94/multi-nginx ./nginx
  - docker build -t seanlucas94/multi-server ./server
  - docker build -t seanlucas94/multi-worker ./worker
  # log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push seanlucas94/multi-client
  - docker push seanlucas94/multi-nginx
  - docker push seanlucas94/multi-server
  - docker push seanlucas94/multi-worker
